# Generated by Django 5.0.6 on 2024-05-19 07:46

import common.kgs
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(default=common.kgs.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=600, null=True)),
                ('transfer_pin', models.CharField(max_length=400, null=True)),
                ('admin_transaction_pin', models.CharField(max_length=400, null=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('lga', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager')], default='Admin', max_length=20)),
                ('user_type', models.CharField(choices=[('Divisional Head', 'Divisional Head'), ('Agent Network Manager', 'Agent Network Manager'), ('Regional Leader', 'Regional Leader'), ('Relationship Officer', 'Relationship Officer'), ('Super Agent', 'Super Agent'), ('Tele-Marketer', 'Tele-Marketer'), ('NSIP-Manager', 'NSIP-Manager'), ('Merchant Manager', 'Merchant Manager'), ('CSO', 'CSO'), ('MaComm', 'MaComm'), ('Risk and Compliance', 'Risk and Compliance'), ('Settlement and Reconciliation', 'Settlement and Reconciliation'), ('OSHIS Supervisor', 'OSHIS Supervisor'), ('Merchant Supervisor', 'Merchant Supervisor')], max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(null=True)),
                ('phone_verified_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='business.region')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='business.state')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('lastname', 'firstname'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=common.kgs.generate_unique_id, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('added_by', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('mother_maiden_name', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('bvn', models.CharField(max_length=200, null=True)),
                ('bvn_verification_data', models.JSONField(null=True)),
                ('nin', models.CharField(max_length=200, null=True)),
                ('kyc_level', models.IntegerField(default=1)),
                ('kyc_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, null=True)),
                ('token_type', models.CharField(choices=[('CreateToken', 'CreateToken'), ('ResetToken', 'ResetToken')], default='ACCOUNT_VERIFICATION', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
