# Generated by Django 5.0.6 on 2024-05-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_level',
            field=models.IntegerField(default=0),
        ),
    ]
