# Generated by Django 5.0.6 on 2024-05-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_kyc_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='divisional_head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='regional_head',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
