# Generated by Django 5.0.6 on 2024-05-20 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_divisional_head_profile_regional_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='divisional_head',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='regional_head',
        ),
        migrations.AddField(
            model_name='user',
            name='divisional_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisional_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='regional_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
