# Generated by Django 5.0.6 on 2024-05-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_divisional_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Admin View Only', 'Admin View Only'), ('Divisional Head', 'Divisional Head'), ('Agent Network Manager', 'Agent Network Manager'), ('Regional Leader', 'Regional Leader'), ('Relationship Officer', 'Relationship Officer'), ('Super Agent', 'Super Agent'), ('Agent', 'Agent'), ('Tele-Marketer', 'Tele-Marketer'), ('NSIP-Manager', 'NSIP-Manager'), ('Merchant Manager', 'Merchant Manager'), ('CSO', 'CSO'), ('MaComm', 'MaComm'), ('Risk and Compliance', 'Risk and Compliance'), ('Settlement and Reconciliation', 'Settlement and Reconciliation'), ('OSHIS Supervisor', 'OSHIS Supervisor'), ('Merchant Supervisor', 'Merchant Supervisor')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
