# Generated by Django 5.0.6 on 2024-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('CreateToken', 'CreateToken'), ('ResetToken', 'ResetToken')], default='CreateToken', max_length=100),
        ),
    ]
